9.10. Код ревью домашнего задания
Serg-E-DEV/PS-JS-BASIC pull request #3
Opened 2024-05-16 10:54 UTC by Serg-E-DEV

2024-05-17 09:45 UTC, GitEsense requested changes
Всё в целом не плохо, но надо доработать функцию конвертера (расширить функционал) и функцию сортировки (убрать модификацию исходного массива)

2024-05-17 09:45 UTC, GitEsense commented on 7-converter/app.js
> +console.log(sum);
Давайте доработаем логику, ведь мы не только рубли конвертируем, но и другие валюты (т.е. не только RUB to EUR / USD, но и другие варианты, например EUR to USD или USD to RUB

2024-05-17 09:45 UTC, GitEsense commented on 8-crypto/app.js
> +}
Обратимость функции как раз и всплывает в моменте "checkPassword", вот что имеется ввиду
```js
function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}
```
т.е. мы для шифрования вызываем "encrypt"  = шифрованный пароль
в проверку передаём "Пароль" и "Шифрованный пароль" и через функцию шифровки мы прогоняем ШИФРОВАННЫЙ пароль, получаем ИСХОДНЫЙ пароль и вот ИСХОДНЫЙ пароль === ПАРОЛЬ 

Обратимость у Вас работает, логика верна, но checkPassword работает по логике "шифратор \ дешифратор" - по сути всё окей и верно, поэтому "приставать не буду", но задание просило другое))

Вот вариант решения на "ознакомление", может будет "интересно"
```js
 // Функция шифрования пароля
function crypt(password) {
    if (!password || !password.length) {
        return NaN;
    }
    const splitedArray = password.split('');
    if (splitedArray.length < 8) {
        return false;
    }

    const middleIndex = Math.floor(splitedArray.length / 2);
    const firstHalf = splitedArray.slice(0, middleIndex).reverse();
    const secondHalf = splitedArray.slice(middleIndex).reverse();
    const length = secondHalf.length;
    [secondHalf[1], secondHalf[length - 2]] = [secondHalf[length - 2], secondHalf[1]];

    const encryptedPassword = firstHalf.concat(secondHalf);
    return encryptedPassword.join('');
}

 // Функция проверки пароля и шифрованного пароля
function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}

 // Функция получения случайного числа из диапазона
function getRandomNumber(min = 0, max = 86) {
    return Math.ceil(Math.random() * (max - min)) + min;
}

 // Функция генерации пароля
function getRandomPassword(length = 12) {
    const symbolArray = Array.from({ length: 87 }, (_, index) => String.fromCharCode(index + 33));
    const password = Array.from({ length }, () => symbolArray[getRandomNumber()]);
    return password.join('');
}

/*
    Вывод в консоль и тестирование
*/

const password = getRandomPassword();
const encrypted = crypt(password);

console.log('Пароль:', password);
console.log('Зашифрованный пароль:', encrypted);
console.log('Проверка пароля:', checkPassword(encrypted, password));

const password2 = getRandomPassword();
const encrypted2 = crypt(password2).substring(1);

console.log('Пароль:', password2);
console.log('Зашифрованный пароль:', encrypted2);
console.log('Проверка пароля:', checkPassword(encrypted2, getRandomPassword()));
```

2024-05-17 09:45 UTC, GitEsense commented on 9-sort-loops/app.js
> +				arr[j + 1] = left;
Вот тут можно воспользоваться трюком обмена переменными 
https://learn.javascript.ru/destructuring-assignment **"Трюк обмена переменными"**
имеет вид
```js
[arr[j + 1], arr[j]] = [arr[j], arr[j+1]]
```

2024-05-17 09:45 UTC, GitEsense commented on 9-sort-loops/app.js
> +console.log(result);
Итого, всю функцию можно было бы записать как-то так
```js
function sortArrayInAscending(incomingArray) {
    for (let i = 0; i < incomingArray.length; i++) {
        for (let j = i + 1; j < incomingArray.length; j++) {
            if (incomingArray[i] > incomingArray[j]) {
                [incomingArray[i], incomingArray[j]] = [incomingArray[j], incomingArray[i]];
            }
        }
    }
    return incomingArray;
}
```
А если добавить немножко "направления сортировки", то что-то вроде такого
```js
function orderTemplate(firstNumber, secondNumber, desc) {
    if (!desc) {
        return firstNumber > secondNumber;
    }
    return firstNumber < secondNumber;
}

function sortArray(array, desc = false) {
    for (let i = 0; i < array.length; i++) {
        for (let j = i; j < array.length; j++) {
            const isExchange = orderTemplate(array[i], array[j], desc);
            if (isExchange) {
                [array[i], array[j]] = [array[j], array[i]];
            }
        }
    }
    return array;
}

console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortArray(numbers));
console.log('Отсортированный по убыванию массив:', sortArray(numbers, true));
```

2024-05-17 09:45 UTC, GitEsense commented on 9-sort-loops/app.js
> +console.log(result);
У Вас функция модифицирует исходный массив, т.е. если взять скажем такой вывод
```js
const arr = [1,3,2,4,0];
console.log(arr) // [1,3,2,4,0]
sort(arr) // [0,1,2,3,4]
console.log(arr) // [0,1,2,3,4]
```
Видно, что arr изменился ( а этого не должно происходить), необходимо доработать функцию, чтобы она не модифицировала исходный массив, а возвращала "новый"

2024-05-17 13:00 UTC, Serg-E-DEV commented on 7-converter/app.js
> +console.log(sum);
Доработал )

2024-05-17 13:01 UTC, Serg-E-DEV commented on 8-crypto/app.js
> +}
Про обратимость большое спасибо. Я и не подумал, что нужно прогнать по тому же алгоритму.

2024-05-17 13:01 UTC, Serg-E-DEV commented on 8-crypto/app.js
> +}
За пример кода спасибо. Сохранил себе.

2024-05-17 13:02 UTC, Serg-E-DEV commented on 9-sort-loops/app.js
> +				arr[j + 1] = left;
Спасибо за трюк! Применил. Сохранил себе!

2024-05-17 13:10 UTC, Serg-E-DEV commented on 9-sort-loops/app.js
> +console.log(result);
Я забыл про порядок! Реализовал немного по-своему. Ваш вариант тоже посмотрел.

2024-05-20 08:23 UTC, GitEsense approved these changes
Всё отлично

2024-05-20 08:23 UTC, GitEsense commented on 7-converter/app.js
> +console.log(sum);
Можно было реализовать несколько проще и через switch case (это и рекомендуется), ведь формально через объект мы ещё не можем делать, тем более через объект становится сииильно проще, вот три разных варианта решения

**Через Объект**
```js
function convertCurrency(baseCurrency, resultCurrency, baseSum) {
    baseCurrency = baseCurrency.toUpperCase()
    resultCurrency = resultCurrency.toUpperCase();
    const exchangeRates = {
        'RUB': 1,
        'USD': 98.9,
        'EUR': 115.01,
    };

    const result = baseSum * exchangeRates[baseCurrency] / exchangeRates[resultCurrency]
    if(isNaN(result)){
        return null
    }

    return `${baseSum.toFixed(2)} ${baseCurrency} -> ${resultCurrency} = ${result.toFixed(2)} (${baseCurrency / resultCurrency})`;
}

sum = convertCurrency('USD', 'RUB', 1000);
console.log(sum);

// error
sum = convertCurrency('RUB', 'BYN', 100);
console.log(sum);
```

**Простой SWITCH CASE:**
```js
function converter(sum, currency, targetCurrency) {
    const USD = 90;
    const EUR = 100;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}

const convertResult = converter(1500, 'rub', 'usd');
console.log(convertResult);
```

**SWITCH CASE с проверками и шаблоном:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = ['RUB', 'EUR', 'USD'];
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();
    const icon = getTargetCurrencyIcon(targetCurrency);

    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }
    if (!ALLOW_CURRENCY_LIST.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!ALLOW_CURRENCY_LIST.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    
    let value = null;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, USD, RUB); break;
                case 'EUR': value = convertSum(sum, USD, EUR); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
        case 'RUB':
            switch (targetCurrency) {
                case 'USD': value = convertSum(sum, RUB, USD); break;
                case 'EUR': value = convertSum(sum, RUB, EUR); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    value = convertSum(sum, EUR, RUB); break;
                case 'USD':
                    value = convertSum(sum, EUR, USD); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
    }

    return messageTemplate(value, icon)
}

const convertResult = converter(1500, 'rub', 'usd');
console.log(convertResult);
```

**Исключительно через массив:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = [['RUB', 1], ['EUR', 112.33], ['USD', 91.33]];
    const flatList = ALLOW_CURRENCY_LIST.flat();
    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    if (!flatList.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!flatList.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    const icon = getTargetCurrencyIcon(targetCurrency);
    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }

    const currentIndex = flatList.indexOf(currency) / 2;
    const targetIndex = flatList.indexOf(targetCurrency) / 2;
    const [, currentValue] = ALLOW_CURRENCY_LIST[currentIndex];
    const [, targetValue] = ALLOW_CURRENCY_LIST[targetIndex];
    const result = convertSum(sum, currentValue, targetValue)
    return messageTemplate(result, icon);
}
```

Ну и запросы для "вывода"
```js
console.log(converter(100, 'RUB', 'USD')); // 1.09 $
console.log(converter(100, 'RUB', 'EUR')); // 0.89 €
console.log(converter(1000, 'EUR', 'USD')); // 1229.94 $
console.log(converter(1000, 'USD', 'EUR')); // 813.05 €
console.log(converter(1000, 'EUR', 'RUB')); // 112330.00 руб

console.log(converter(1500, 'EUR', 'RUB'));
console.log(converter(1500, 'USD', 'RUB'));

console.log(converter(10, 'RUB', 'EUR'));
console.log(converter(10, 'USD', 'EUR'));

console.log(converter(10, 'RUB', 'EURU'));
console.log(converter(10, 'USD', 'EUR'));

console.log(converter(10, 'RUB', 'EUR'));
console.log(converter(10, 'USDTY', 'EUR'));
```

2024-05-21 14:21 UTC, Serg-E-DEV commented
Спасибо! Про switch и промежуточную конвертацию понял

2024-05-21 14:21 UTC, merged