19.2. Код ревью домашнего задания
Serg-E-DEV/PS-JS-BASIC pull request #6
Opened 2024-05-27 15:01 UTC by Serg-E-DEV

2024-05-31 08:46 UTC, GitEsense requested changes
Используйте EVENT, всплытие событий, чтобы не городить "сотни" одинаковых элементов, достаточно иметь "значение" или атрибут, по которому обращаться (например data-action="...") ловить событие от родителя и т.д.

2024-05-31 08:46 UTC, GitEsense commented on 17-calc/index.html
> +		</div>
Воспользуйтесь всплытием событий, Вы на каждый button будете вешать функцию? - не особо прокатит, если их будет 1000 например.

2024-06-02 03:49 UTC, Serg-E-DEV commented on 17-calc/index.html
> +		</div>
Спасибо. Сделал такую реализацию. Она без всплытия, а с автоматическим назначением слушателей. Так пойдёт? Или это тоже малоэффективно, получается?

2024-06-02 04:01 UTC, Serg-E-DEV commented on 17-calc/index.html
> +		</div>
Теперь разобрался со всплытием. Реализовал через него. Получается один слушатель вместо 1000.

2024-06-05 14:08 UTC, GitEsense approved these changes
Ну вот да, примерно так, хотя я бы сделал ещё "жжёще"
```js
`use strict`;
const page = {
    panel: document.querySelector('.panel'),
    notification: document.querySelector('.notification'),
    inputs: {
        num1: document.querySelector('[name="num1"]'),
        num2: document.querySelector('[name="num2"]'),
    },
};

function onActionClick(event) {
    const action = event.target.innerText;
    const elements = [page.inputs.num1, page.inputs.num2];
    const data = validateAndGetInputData(elements);
    if (!data) {
        return (page.panel.innerText = 'Не введены все числа');
    }
    const result = calculate(data[0], data[1], action);
    resetInputs(elements);
    page.panel.innerText = `${data[0]} ${action} ${data[1]} = ${result}`;
    page.notification.classList.remove('notification_hidden');
}

function resetInputs(elements) {
    for (const elem of elements) {
        elem.value = '';
    }
}

function validateAndGetInputData(elements) {
    let isValid = true;
    const result = [];
    for (const elem of elements) {
        const elemValue = elem.value;
        elem.classList.remove('error');
        if (!elemValue) {
            page.notification.classList.add('notification_hidden');
            elem.classList.add('error');
            isValid = false;
        }
        result.push(Number(elemValue));
    }

    if (!isValid) {
        return false;
    }
    return result;
}

function calculate(a, b, char) {
    switch (char) {
        case '+': {
            return a + b;
        }
        case '-': {
            return a - b;
        }
        case '/': {
            if (b === 0) {
                return 'Нельзя делить на ноль';
            }
            return (a / b).toFixed(2);
        }
        case '*': {
            return a * b.toFixed(2);
        }
    }
}
```
```html
<body style="background-color: #1c1b21; text-align: center">
        <img class="logo" src="./logo.svg" alt="" />
        <div>
            <input type="number" autofocus name="num1" class="input" />
            <input type="number" name="num2" class="input" />
            <div class="button__list" onclick="onActionClick(event)">
                <button class="button">+</button>
                <button class="button">-</button>
                <button class="button">*</button>
                <button class="button">/</button>
            </div>
        </div>
        <div class="panel">
            Здесь будет результат вычислений, пожалуйста введите числа и
            выберите действие
        </div>

        <div class="notification notification_hidden">Вычисление окончено!</div>
        <div class="test"></div>
        <script src="./app.js"></script>
    </body>
```
```css
.panel {
    font-size: 18px;
    color: white;
    background: rgba(255, 255, 255, 0.05);
    border-radius: 10px;
    padding: 40px;
    margin-top: 20px;
}
form > div {
    padding-top: 10px;
}
.logo {
    height: 15%;
    width: 15%;
    margin-bottom: 10px;
}

.notification {
    font-size: 16px;
    color: white;
    margin: 20px;
}
.notification_hidden {
    display: none;
}
.button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    box-sizing: border-box;
    cursor: pointer;
    transition: all 0.2s;
    text-align: center;
    border-radius: 10px;
    background: #6c38cc;
    color: white;
    border: none;
    padding: 20px 40px;
}

.button:hover {
    background-color: #844fe6;
}

.input {
    box-sizing: border-box;
    padding: 15px 16px;
    color: white;
    border: 1px solid rgba(212, 212, 212, 0.05);
    border-radius: 10px;
    background: rgba(255, 255, 255, 0.05);
    height: 56px;
    font-size: 18px;
    line-height: 21px;
    outline: none;
    box-shadow: none;
}
.button__list {
    padding-top: 10px;
}
.error {
    border: 1px solid red;
}
```

А можно и вот так
```js
const pages = {
                body: document.querySelector('body'),
                inputs: {
                    first: document.querySelector('input[data-number="first"]'),
                    second: document.querySelector('input[data-number="second"]'),
                },
                result: document.querySelector('.result'),
                action: '',
            };
            const actions = {
                '+': (a, b) => `${a} + ${b} = ${a + b}`,
                '-': (a, b) => `${a} - ${b} = ${a - b}`,
                '/': (a, b) => (b !== 0 ? `${a} / ${b} = ${a / b}` : 'Нельзя делить на ноль'),
                '*': (a, b) => `${a} * ${b} = ${a * b}`,
            };
            function calc(event) {
                if (event.target.tagName !== 'BUTTON') {
                    return;
                }
                const { action } = event.target.dataset;

                const {
                    first: { value: a },
                    second: { value: b },
                } = pages.inputs;
                if (action === '=') {
                    return calcucate(a, b);
                } else if (action === 'reset') {
                    return resetInputs();
                }
                pages.action = action;
            }
            function calcucate(a, b) {
                if (!a || !b) {
                    pages.result.innerHTML = 'Не введено одно из чисел';
                    return;
                }
                const result = actions[pages.action];
                pages.result.innerHTML = result(...[a, b].map(parseFloat)) ?? 'Результат не определён';
                return;
            }
            function resetInputs() {
                Object.keys(pages.inputs).map((x) => (pages.inputs[x].value = null));
                pages.result.innerHTML = '';
            }
```

2024-06-06 06:08 UTC, Serg-E-DEV commented
А можете HTML  к последнему JS добавить? Чтобы я посмотрел if (action === '=')

2024-06-06 07:09 UTC, merged